name: Deploy to FTP Server

on:
  push:
    branches:
      - main # Adjust to your branch name

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy via FTP
      - name: 📂 Sync files to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftp.ititans.com
          username: zainjaved@ititans.com
          password: ${{ secrets.FTP_SECRET }}
          local-dir: ./ # This is the directory containing your code
          server-dir: ititans.com/public_html/ # This is the target directory on the FTP Server
          exclude: |
            **/.git**
            **/blog/**
            **/blog**
